[build]
  [[steps]]
  name = "Build Angular"
  builder = "node"
  dir = "project-todo-app"
  cmd = "npm install && npm run build"

  [[steps]]
  name = "Build Spring Boot"
  builder = "java"
  dir = "Project-Management"
  [steps.env]
  MAVEN_OPTS = "-Dmaven.repo.local=/opt/maven"

[start]
  [[steps]]
  name = "Start Spring Boot"
  cmd = "java -jar Project-Management/target/*.jar"

  [[steps]]
  name = "Serve Angular"
  cmd = "npx http-server project-todo-app/dist"
